//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDjpPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDjpPlugin.Resources.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Align Assignments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_ALIGN_ASSIGMENTS {
            get {
                return ResourceManager.GetString("CATEGORY_ALIGN_ASSIGMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always Compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("CATEGORY_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caluclation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_CALCULATE {
            get {
                return ResourceManager.GetString("CATEGORY_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_FOLDING {
            get {
                return ResourceManager.GetString("CATEGORY_FOLDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_MOVE_LINE {
            get {
                return ResourceManager.GetString("CATEGORY_MOVE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_MOVE_WORD {
            get {
                return ResourceManager.GetString("CATEGORY_MOVE_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_SEARCH {
            get {
                return ResourceManager.GetString("CATEGORY_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Align Assignments&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALIGN_ASSIGNMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALIGN_ASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables Change Always Compile after Compile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALWAYS_COMP_AFTER_COMP {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALWAYS_COMP_AFTER_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Set &quot;Always Compile&quot; as current file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Caluclate Selection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_CALC_SELECTION {
            get {
                return ResourceManager.GetString("DESCRIPTION_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Expand All Comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_EXPAND_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_EXPAND_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Flod All Comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_FOLD_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_FOLD_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide the &quot;Custom&quot; menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_HIDE_MENU {
            get {
                return ResourceManager.GetString("DESCRIPTION_HIDE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Move Line Down. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_MOVE_LINE_DOWN {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOVE_LINE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Move Line Up. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_MOVE_LINE_UP {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOVE_LINE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Next Word. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_NEXT_WORD {
            get {
                return ResourceManager.GetString("DESCRIPTION_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Prev Word. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_PREV_WORD {
            get {
                return ResourceManager.GetString("DESCRIPTION_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Search Identifier Next. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("DESCRIPTION_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of the Search Identifier Prev. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_SEARCH_PREV {
            get {
                return ResourceManager.GetString("DESCRIPTION_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables toggle Fold and Expand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_TOGGLE_FOLD_EXPAND {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOGGLE_FOLD_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select on Move Word. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_WORD_SELECT {
            get {
                return ResourceManager.GetString("DESCRIPTION_WORD_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlashDevelop.jp plugin. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_NOT_FOUND {
            get {
                return ResourceManager.GetString("INFO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A&amp;lign Assignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_ALIGN_ASSIGNMENT {
            get {
                return ResourceManager.GetString("LABEL_ALIGN_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Always Compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("LABEL_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Calcurate Selction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_CALC_SELECTION {
            get {
                return ResourceManager.GetString("LABEL_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Expand All Block Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_EXPAND_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("LABEL_EXPAND_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Fold All Block Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_FOLD_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("LABEL_FOLD_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C&amp;ustom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_MENU {
            get {
                return ResourceManager.GetString("LABEL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Line &amp;Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_LINE {
            get {
                return ResourceManager.GetString("LABEL_NEXT_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Next Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_WORD {
            get {
                return ResourceManager.GetString("LABEL_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Line &amp;Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_LINE {
            get {
                return ResourceManager.GetString("LABEL_PREV_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Prev Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_WORD {
            get {
                return ResourceManager.GetString("LABEL_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Identifier &amp;Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("LABEL_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Identifier &amp;Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_SEARCH_PREV {
            get {
                return ResourceManager.GetString("LABEL_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identifier is Not Found:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Calcurate selection&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_CALC_SELECTION {
            get {
                return ResourceManager.GetString("NAME_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Next Word&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_NEXT_WORD {
            get {
                return ResourceManager.GetString("NAME_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Prev Word&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_PREV_WORD {
            get {
                return ResourceManager.GetString("NAME_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Search Identifier Next&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("NAME_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut of &quot;Search Identifier Prev&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_SEARCH_PREV {
            get {
                return ResourceManager.GetString("NAME_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TITLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TITLE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
