//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDjpPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDjpPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Always Compileに設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("LABEL_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_MENU {
            get {
                return ResourceManager.GetString("LABEL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の行へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_LINE {
            get {
                return ResourceManager.GetString("LABEL_NEXT_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のワードへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_WORD {
            get {
                return ResourceManager.GetString("LABEL_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前の行へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_LINE {
            get {
                return ResourceManager.GetString("LABEL_PREV_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のワードへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_WORD {
            get {
                return ResourceManager.GetString("LABEL_PREV_WORD", resourceCulture);
            }
        }
    }
}
