//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDjpPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja_JP() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDjpPlugin.Resources.ja_JP", typeof(ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コード整列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_ALIGN_ASSIGMENTS {
            get {
                return ResourceManager.GetString("CATEGORY_ALIGN_ASSIGMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always Compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("CATEGORY_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_CALCULATE {
            get {
                return ResourceManager.GetString("CATEGORY_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   折りたたみ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_FOLDING {
            get {
                return ResourceManager.GetString("CATEGORY_FOLDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_MOVE_LINE {
            get {
                return ResourceManager.GetString("CATEGORY_MOVE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワード移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_MOVE_WORD {
            get {
                return ResourceManager.GetString("CATEGORY_MOVE_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CATEGORY_SEARCH {
            get {
                return ResourceManager.GetString("CATEGORY_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コード整列のショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALIGN_ASSIGNMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALIGN_ASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り替えた後コンパイルする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALWAYS_COMP_AFTER_COMP {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALWAYS_COMP_AFTER_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always Compile を現在のドキュメントに設定するショートカット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("DESCRIPTION_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲を計算のショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_CALC_SELECTION {
            get {
                return ResourceManager.GetString("DESCRIPTION_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての複数コメント行を展開する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_EXPAND_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_EXPAND_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての複数コメント行を折りたたむ。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_FOLD_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("DESCRIPTION_FOLD_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;カスタム&quot;メニューを非表示にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_HIDE_MENU {
            get {
                return ResourceManager.GetString("DESCRIPTION_HIDE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下に行を移動する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_MOVE_LINE_DOWN {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOVE_LINE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上に行を移動する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_MOVE_LINE_UP {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOVE_LINE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のワードに移動するショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_NEXT_WORD {
            get {
                return ResourceManager.GetString("DESCRIPTION_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のワードに移動するショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_PREV_WORD {
            get {
                return ResourceManager.GetString("DESCRIPTION_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を識別子検索するショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("DESCRIPTION_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を識別子検索するショートカットの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_SEARCH_PREV {
            get {
                return ResourceManager.GetString("DESCRIPTION_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントの折りたたみ/展開をトグルさせるようにする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_TOGGLE_FOLD_EXPAND {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOGGLE_FOLD_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動した際にワードをセレクトする設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESCRIPTION_WORD_SELECT {
            get {
                return ResourceManager.GetString("DESCRIPTION_WORD_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlashDevelop.jpプラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {$0} は見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_NOT_FOUND {
            get {
                return ResourceManager.GetString("INFO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードの整列(&amp;L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_ALIGN_ASSIGNMENT {
            get {
                return ResourceManager.GetString("LABEL_ALIGN_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always Compileに設定(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_ALWAYS_COMPILE {
            get {
                return ResourceManager.GetString("LABEL_ALWAYS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲を計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_CALC_SELECTION {
            get {
                return ResourceManager.GetString("LABEL_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックコメントをすべて展開(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_EXPAND_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("LABEL_EXPAND_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックコメントをすべて折りたたむ(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_FOLD_ALL_COMMENTS {
            get {
                return ResourceManager.GetString("LABEL_FOLD_ALL_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_MENU {
            get {
                return ResourceManager.GetString("LABEL_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の行へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_LINE {
            get {
                return ResourceManager.GetString("LABEL_NEXT_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のワードへ(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_NEXT_WORD {
            get {
                return ResourceManager.GetString("LABEL_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前の行へ(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_LINE {
            get {
                return ResourceManager.GetString("LABEL_PREV_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のワードへ(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_PREV_WORD {
            get {
                return ResourceManager.GetString("LABEL_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を識別子検索(&amp;K) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("LABEL_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を識別子検索(&amp;J) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LABEL_SEARCH_PREV {
            get {
                return ResourceManager.GetString("LABEL_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の指定された識別子は見つかりませんでした:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲を計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_CALC_SELECTION {
            get {
                return ResourceManager.GetString("NAME_CALC_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のワードへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_NEXT_WORD {
            get {
                return ResourceManager.GetString("NAME_NEXT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のワードへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_PREV_WORD {
            get {
                return ResourceManager.GetString("NAME_PREV_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を識別子検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_SEARCH_NEXT {
            get {
                return ResourceManager.GetString("NAME_SEARCH_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を識別子検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAME_SEARCH_PREV {
            get {
                return ResourceManager.GetString("NAME_SEARCH_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TITLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TITLE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
